#!/usr/bin/env bash

if [[ $# == 1 && $1 == devices ]]; then
  echo -e "23456789     fastboot"
elif [[ $# == 2 || $1 == devices || $2 == -l ]]; then
  echo "23456789     fastboot usb:1-1.4.4"
else
  echo -e "FAIL-DEVICES-NOT-CALLED\tFAILFAILFAIL"
  exit 1
fi

