{{/* renovate: datasource=github-releases depName=junegunn/fzf */}}
{{- $fzfVersion := "0.73.1" -}}
{{/* renovate: datasource=github-releases depName=rbenv/rbenv */}}
{{- $rbenvVersion := "1.3.2" -}}
{{/* renovate: datasource=github-releases depName=rbenv/ruby-build */}}
{{- $rubyBuildVersion := "20251225" -}}
{{/* renovate: datasource=github-releases depName=jdx/mise */}}
{{- $miseVersion := "v2026.5.12" -}}
{{/* renovate: datasource=git-refs depName=lincheney/fzf-tab-completion packageName=https://github.com/lincheney/fzf-tab-completion currentValue=master */}}
{{- $fzfTabCompletionCommit := "8ba35e65bb3792759bf17c134ce04120e5940555" -}}
{{/* renovate: datasource=github-tags depName=rcaloras/bash-preexec */}}
{{- $bashPreexecVersion := "0.6.0" -}}
{{/* renovate: datasource=git-refs depName=seebi/dircolors-solarized packageName=https://github.com/seebi/dircolors-solarized currentValue=master */}}
{{- $dircolorsSolarizedCommit := "38971d217512a23391139fcee2a520eba7cddf37" -}}
{{/* renovate: datasource=github-tags depName=tmux-plugins/tpm */}}
{{- $tpmVersion := "v3.1.0" -}}
{{/* renovate: datasource=git-refs depName=nornagon/git-rebase-all packageName=https://github.com/nornagon/git-rebase-all currentValue=master */}}
{{- $gitRebaseAllCommit := "a8639a142dd5d672586a6c3b67c1b9288dab586b" -}}
{{/* renovate: datasource=github-tags depName=paldepind/projectdo */}}
{{- $projectdoVersion := "v1.0.0" -}}
{{/* renovate: datasource=github-tags depName=junegunn/vim-plug */}}
{{- $vimPlugVersion := "0.14.0" -}}
{{/* renovate: datasource=git-refs depName=altercation/vim-colors-solarized packageName=https://github.com/altercation/vim-colors-solarized currentValue=master */}}
{{- $vimColorsSolarizedCommit := "528a59f26d12278698bb946f8fb82a63711eec21" -}}

[".local/bin/mise"]
    type = "archive-file"
    url = "https://github.com/jdx/mise/releases/download/{{ $miseVersion }}/mise-{{ $miseVersion }}-{{ .chezmoi.os | replaceAllRegex "darwin" "macos" }}-{{ .chezmoi.arch | replaceAllRegex "amd64" "x64" }}.tar.gz"
    stripComponents = 1
    path = "bin/mise"
[".fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/refs/tags/v{{ $fzfVersion }}.tar.gz"
    exact = true
    stripComponents = 1
[".fzf/bin"]
    type = "archive"
    exact = true
    url = "https://github.com/junegunn/fzf/releases/download/v{{ $fzfVersion }}/fzf-{{ $fzfVersion }}-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
[".fzf-tab-completion"]
    type = "archive"
    url = "https://github.com/lincheney/fzf-tab-completion/archive/{{ $fzfTabCompletionCommit }}.zip"
    exact = true
    stripComponents = 1
[".bash-preexec"]
    type = "archive"
    url = "https://github.com/rcaloras/bash-preexec/archive/refs/tags/{{ $bashPreexecVersion }}.zip"
    exact = true
    stripComponents = 1
[".dircolors-solarized"]
    type = "archive"
    url = "https://github.com/seebi/dircolors-solarized/archive/{{ $dircolorsSolarizedCommit }}.zip"
    exact = true
    stripComponents = 1
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/{{ $tpmVersion }}.zip"
    exact = true
    stripComponents = 1
["bin/git-rebase-all"]
    type = "archive-file"
    url = "https://github.com/nornagon/git-rebase-all/archive/{{ $gitRebaseAllCommit }}.zip"
    stripComponents = 1
    path = "git-rebase-all"
["bin/projectdo"]
    type = "archive-file"
    url = "https://github.com/paldepind/projectdo/archive/refs/tags/{{ $projectdoVersion }}.zip"
    stripComponents = 1
    path = "projectdo"
[".rbenv"]
    type = "archive"
    url = "https://github.com/rbenv/rbenv/archive/refs/tags/v{{ $rbenvVersion }}.zip"
    stripComponents = 1
    refreshPeriod = "168h"
[".ruby-build"]
    type = "archive"
    url = "https://github.com/rbenv/ruby-build/archive/refs/tags/v{{ $rubyBuildVersion }}.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/{{ $vimPlugVersion }}/plug.vim"
[".vim/colors/solarized.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/altercation/vim-colors-solarized/{{ $vimColorsSolarizedCommit }}/colors/solarized.vim"

# https://github.com/jorgebucaran/fisher.git
