before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bash-completion
install: git clone --depth 1 https://github.com/sstephenson/bats.git
script: PATH="./bats/bin:$PATH" bats --tap test
notifications:
  email:
    on_success: never
