sudo: false

addons:
  apt:
    packages:
      - bash-completion

install: git clone --depth 1 https://github.com/sstephenson/bats.git
script: PATH="./bats/bin:$PATH" bats --tap test
notifications:
  email:
    on_success: never
