sudo: false

addons:
  apt:
    packages:
      - bash-completion

install:
  - gem install bashcov
  - gem install coveralls

script: PATH="$PWD/bats/bin:$PATH" bashcov -- bats --tap test

notifications:
  email:
    on_success: never
