sudo: false

addons:
  apt:
    packages:
      - bash-completion
      - fish

install:
  - gem install bashcov
  - gem install coveralls

script: bashcov -- ./bats/bin/bats --tap test

notifications:
  email:
    on_success: never
