# renovate: datasource=github-releases depName=junegunn/fzf
{{ $fzfVersion := "0.62.0" -}}
# renovate: datasource=github-releases depName=rbenv/rbenv
{{ $rbenvVersion := "1.3.2" -}}

[".fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/refs/tags/v{{ $fzfVersion }}.tar.gz"
    exact = true
    stripComponents = 1
[".fzf/bin"]
    type = "archive"
    exact = true
    url = "https://github.com/junegunn/fzf/releases/download/v{{ $fzfVersion }}/fzf-{{ $fzfVersion }}-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
[".fzf-tab-completion"]
    type = "archive"
    url = "https://github.com/lincheney/fzf-tab-completion/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".bash-preexec"]
    type = "archive"
    url = "https://github.com/rcaloras/bash-preexec/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".dircolors-solarized"]
    type = "archive"
    url = "https://github.com/seebi/dircolors-solarized/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["bin/git-rebase-all"]
    type = "archive-file"
    url = "https://github.com/nornagon/git-rebase-all/archive/refs/heads/master.zip"
    stripComponents = 1
    path = "git-rebase-all"
[".neobundle.vim"]
    type = "archive"
    url = "https://github.com/Shougo/neobundle.vim/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["bin/projectdo"]
    type = "archive-file"
    url = "https://github.com/paldepind/projectdo/archive/refs/heads/master.zip"
    stripComponents = 1
    path = "projectdo"

# https://github.com/jorgebucaran/fisher.git

