#!/usr/bin/env bash

if [[ $# == 1 && $1 == devices ]]; then
  echo "12345678 fastboot1"
  echo "23456789 fastboot2"
elif [[ $# == 2 || $1 == devices || $2 == -l ]]; then
  echo "12345678 fastboot1 usb:1-1.4.4"
  echo "23456789 fastboot2 usb:2-3.4.6"
else
  echo -e "FAIL-DEVICES-NOT-CALLED\tFAILFAILFAIL"
  exit 1
fi

